"""add missing model tables

Revision ID: 554c6950560a
Revises: f0a1b2c3d4e5
Create Date: 2026-07-04 12:29:23.089968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '554c6950560a'
down_revision: Union[str, None] = 'f0a1b2c3d4e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_kpis',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('target_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('trend', sa.String(length=20), nullable=False),
    sa.Column('trend_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analytics_kpis')),
    comment='Key Performance Indicators tracking'
    )
    op.create_index(op.f('ix_analytics_kpis_created_by'), 'analytics_kpis', ['created_by'], unique=False)
    op.create_index(op.f('ix_analytics_kpis_deleted_at'), 'analytics_kpis', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_analytics_kpis_updated_by'), 'analytics_kpis', ['updated_by'], unique=False)
    op.create_table('cert_certificates',
    sa.Column('certificate_number', sa.String(length=50), nullable=False),
    sa.Column('student_id', sa.String(length=100), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=False),
    sa.Column('program', sa.String(length=255), nullable=False),
    sa.Column('batch', sa.String(length=100), nullable=False),
    sa.Column('mentor_name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('generated_by', sa.String(length=100), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('qr_code_url', sa.String(length=500), nullable=False),
    sa.Column('verification_url', sa.String(length=500), nullable=False),
    sa.Column('digital_signature_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cert_certificates')),
    comment='Student certificates'
    )
    op.create_index(op.f('ix_cert_certificates_certificate_number'), 'cert_certificates', ['certificate_number'], unique=True)
    op.create_index(op.f('ix_cert_certificates_created_by'), 'cert_certificates', ['created_by'], unique=False)
    op.create_index(op.f('ix_cert_certificates_deleted_at'), 'cert_certificates', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_cert_certificates_updated_by'), 'cert_certificates', ['updated_by'], unique=False)
    op.create_table('cert_verification_requests',
    sa.Column('certificate_number', sa.String(length=50), nullable=False),
    sa.Column('requested_by_ip', sa.String(length=50), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=False),
    sa.Column('result', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cert_verification_requests')),
    comment='Log of certificate verification requests'
    )
    op.create_index(op.f('ix_cert_verification_requests_certificate_number'), 'cert_verification_requests', ['certificate_number'], unique=False)
    op.create_index(op.f('ix_cert_verification_requests_created_by'), 'cert_verification_requests', ['created_by'], unique=False)
    op.create_index(op.f('ix_cert_verification_requests_deleted_at'), 'cert_verification_requests', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_cert_verification_requests_updated_by'), 'cert_verification_requests', ['updated_by'], unique=False)
    op.create_table('comm_calendar_events',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('meeting_link', sa.String(length=500), nullable=True),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comm_calendar_events')),
    comment='Calendar scheduling events'
    )
    op.create_index(op.f('ix_comm_calendar_events_created_by'), 'comm_calendar_events', ['created_by'], unique=False)
    op.create_index(op.f('ix_comm_calendar_events_deleted_at'), 'comm_calendar_events', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_comm_calendar_events_updated_by'), 'comm_calendar_events', ['updated_by'], unique=False)
    op.create_table('quiz_assessments',
    sa.Column('batch_id', sa.String(length=50), nullable=False),
    sa.Column('frontend_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('passing_marks', sa.Integer(), nullable=False),
    sa.Column('negative_marking', sa.Boolean(), nullable=False),
    sa.Column('security_settings', sa.JSON(), nullable=False),
    sa.Column('questions', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_assessments')),
    comment='Quiz configuration and metadata'
    )
    op.create_index(op.f('ix_quiz_assessments_created_by'), 'quiz_assessments', ['created_by'], unique=False)
    op.create_index(op.f('ix_quiz_assessments_deleted_at'), 'quiz_assessments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_quiz_assessments_frontend_id'), 'quiz_assessments', ['frontend_id'], unique=True)
    op.create_index(op.f('ix_quiz_assessments_updated_by'), 'quiz_assessments', ['updated_by'], unique=False)
    op.create_table('sys_reports',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('generated_by', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('download_url', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sys_reports')),
    comment='Generated report logs and metadata'
    )
    op.create_index(op.f('ix_sys_reports_created_by'), 'sys_reports', ['created_by'], unique=False)
    op.create_index(op.f('ix_sys_reports_deleted_at'), 'sys_reports', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_sys_reports_updated_by'), 'sys_reports', ['updated_by'], unique=False)
    op.create_table('prod_bookmarks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name=op.f('fk_prod_bookmarks_user_id_auth_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prod_bookmarks')),
    comment='Personal bookmarked external links'
    )
    op.create_index(op.f('ix_prod_bookmarks_created_by'), 'prod_bookmarks', ['created_by'], unique=False)
    op.create_index(op.f('ix_prod_bookmarks_deleted_at'), 'prod_bookmarks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_prod_bookmarks_updated_by'), 'prod_bookmarks', ['updated_by'], unique=False)
    op.create_index(op.f('ix_prod_bookmarks_user_id'), 'prod_bookmarks', ['user_id'], unique=False)
    op.create_table('prod_personal_tasks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('due_date', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name=op.f('fk_prod_personal_tasks_user_id_auth_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prod_personal_tasks')),
    comment='Personal to-do tasks for each user'
    )
    op.create_index(op.f('ix_prod_personal_tasks_created_by'), 'prod_personal_tasks', ['created_by'], unique=False)
    op.create_index(op.f('ix_prod_personal_tasks_deleted_at'), 'prod_personal_tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_prod_personal_tasks_updated_by'), 'prod_personal_tasks', ['updated_by'], unique=False)
    op.create_index(op.f('ix_prod_personal_tasks_user_id'), 'prod_personal_tasks', ['user_id'], unique=False)
    op.create_table('prod_sticky_notes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name=op.f('fk_prod_sticky_notes_user_id_auth_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prod_sticky_notes')),
    comment='Personal sticky notes for quick jotting'
    )
    op.create_index(op.f('ix_prod_sticky_notes_created_by'), 'prod_sticky_notes', ['created_by'], unique=False)
    op.create_index(op.f('ix_prod_sticky_notes_deleted_at'), 'prod_sticky_notes', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_prod_sticky_notes_updated_by'), 'prod_sticky_notes', ['updated_by'], unique=False)
    op.create_index(op.f('ix_prod_sticky_notes_user_id'), 'prod_sticky_notes', ['user_id'], unique=False)
    op.create_table('quiz_submissions',
    sa.Column('assessment_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.String(length=50), nullable=False),
    sa.Column('student_name', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('question_analysis', sa.JSON(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['assessment_id'], ['quiz_assessments.id'], name=op.f('fk_quiz_submissions_assessment_id_quiz_assessments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quiz_submissions')),
    comment='Candidate attempts for quizzes'
    )
    op.create_index(op.f('ix_quiz_submissions_assessment_id'), 'quiz_submissions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_quiz_submissions_created_by'), 'quiz_submissions', ['created_by'], unique=False)
    op.create_index(op.f('ix_quiz_submissions_deleted_at'), 'quiz_submissions', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_quiz_submissions_student_id'), 'quiz_submissions', ['student_id'], unique=False)
    op.create_index(op.f('ix_quiz_submissions_updated_by'), 'quiz_submissions', ['updated_by'], unique=False)
    op.create_table('rbac_role_modules',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['module_id'], ['rbac_modules.id'], name=op.f('fk_rbac_role_modules_module_id_rbac_modules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], name=op.f('fk_rbac_role_modules_role_id_rbac_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rbac_role_modules')),
    sa.UniqueConstraint('role_id', 'module_id', name='uq_rbac_role_module'),
    comment='Junction mapping roles to modules'
    )
    op.create_index(op.f('ix_rbac_role_modules_created_by'), 'rbac_role_modules', ['created_by'], unique=False)
    op.create_index(op.f('ix_rbac_role_modules_deleted_at'), 'rbac_role_modules', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_rbac_role_modules_module_id'), 'rbac_role_modules', ['module_id'], unique=False)
    op.create_index(op.f('ix_rbac_role_modules_role_id'), 'rbac_role_modules', ['role_id'], unique=False)
    op.create_index(op.f('ix_rbac_role_modules_updated_by'), 'rbac_role_modules', ['updated_by'], unique=False)
    op.create_table('rbac_user_modules',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['module_id'], ['rbac_modules.id'], name=op.f('fk_rbac_user_modules_module_id_rbac_modules'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name=op.f('fk_rbac_user_modules_user_id_auth_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rbac_user_modules')),
    sa.UniqueConstraint('user_id', 'module_id', name='uq_rbac_user_module'),
    comment='Junction mapping explicit module grants to users'
    )
    op.create_index(op.f('ix_rbac_user_modules_created_by'), 'rbac_user_modules', ['created_by'], unique=False)
    op.create_index(op.f('ix_rbac_user_modules_deleted_at'), 'rbac_user_modules', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_rbac_user_modules_module_id'), 'rbac_user_modules', ['module_id'], unique=False)
    op.create_index(op.f('ix_rbac_user_modules_updated_by'), 'rbac_user_modules', ['updated_by'], unique=False)
    op.create_index(op.f('ix_rbac_user_modules_user_id'), 'rbac_user_modules', ['user_id'], unique=False)
    op.create_table('alum_placement_opportunities',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('package_lpa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, comment='Unique identifier for the record'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Timestamp when the record was last updated'),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='UUID of the user who created this record (Soft FK)'),
    sa.Column('updated_by', sa.UUID(), nullable=True, comment='UUID of the user who last updated this record (Soft FK)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when the record was soft-deleted. NULL means active.'),
    sa.Column('version_id', sa.Integer(), nullable=False, comment='Optimistic locking version number'),
    sa.ForeignKeyConstraint(['company_id'], ['comp_companies.id'], name=op.f('fk_alum_placement_opportunities_company_id_comp_companies'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alum_placement_opportunities')),
    comment='Corporate job placement opportunities'
    )
    op.create_index(op.f('ix_alum_placement_opportunities_company_id'), 'alum_placement_opportunities', ['company_id'], unique=False)
    op.create_index(op.f('ix_alum_placement_opportunities_created_by'), 'alum_placement_opportunities', ['created_by'], unique=False)
    op.create_index(op.f('ix_alum_placement_opportunities_deleted_at'), 'alum_placement_opportunities', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_alum_placement_opportunities_updated_by'), 'alum_placement_opportunities', ['updated_by'], unique=False)
    op.add_column('comm_email_templates', sa.Column('status', sa.String(length=50), server_default='Active', nullable=False))
    op.alter_column('fin_payment_transactions', 'currency_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('fin_payment_transactions', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='created, authorized, captured, failed, refunded',
               existing_comment='SUCCESS, FAILED, PENDING',
               existing_nullable=False)
    op.alter_column('fin_payment_transactions', 'gateway_response',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_fin_payment_transactions_order_id'), 'fin_payment_transactions', type_='unique')
    op.drop_constraint(op.f('uq_fin_payment_transactions_razorpay_order_id'), 'fin_payment_transactions', type_='unique')
    op.drop_constraint(op.f('uq_fin_payment_transactions_razorpay_payment_id'), 'fin_payment_transactions', type_='unique')
    op.drop_index(op.f('ix_fin_payment_transactions_order_id'), table_name='fin_payment_transactions')
    op.create_index(op.f('ix_fin_payment_transactions_order_id'), 'fin_payment_transactions', ['order_id'], unique=True)
    op.create_index(op.f('ix_fin_payment_transactions_razorpay_order_id'), 'fin_payment_transactions', ['razorpay_order_id'], unique=True)
    op.create_index(op.f('ix_fin_payment_transactions_razorpay_payment_id'), 'fin_payment_transactions', ['razorpay_payment_id'], unique=True)
    op.create_table_comment(
        'fin_payment_transactions',
        'Detailed log of Razorpay payment records',
        existing_comment='Detailed log of payment gateway transactions',
        schema=None
    )
    op.alter_column('intern_applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='PENDING, UNDER_REVIEW, ACCEPTED, REJECTED',
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_intern_certificates_certificate_number'), 'intern_certificates', ['certificate_number'])
    op.add_column('profile_employees', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('profile_employees', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('profile_employees', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('profile_employees', sa.Column('phone', sa.String(length=20), nullable=True))
    op.alter_column('profile_employees', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_profile_employees_email'), 'profile_employees', ['email'], unique=True)
    op.drop_constraint(op.f('fk_profile_employees_user_id_auth_users'), 'profile_employees', type_='foreignkey')
    op.create_foreign_key(op.f('fk_profile_employees_user_id_auth_users'), 'profile_employees', 'auth_users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('sup_tickets', sa.Column('ticket_number', sa.String(length=50), nullable=False))
    op.add_column('sup_tickets', sa.Column('department', sa.String(length=100), nullable=True))
    op.add_column('sup_tickets', sa.Column('resolution_remark', sa.Text(), nullable=True))
    op.add_column('sup_tickets', sa.Column('satisfaction_status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_sup_tickets_ticket_number'), 'sup_tickets', ['ticket_number'], unique=True)
    op.drop_column('sys_verification_records', 'aadhaar_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sys_verification_records', sa.Column('aadhaar_number', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_sup_tickets_ticket_number'), table_name='sup_tickets')
    op.drop_column('sup_tickets', 'satisfaction_status')
    op.drop_column('sup_tickets', 'resolution_remark')
    op.drop_column('sup_tickets', 'department')
    op.drop_column('sup_tickets', 'ticket_number')
    op.drop_constraint(op.f('fk_profile_employees_user_id_auth_users'), 'profile_employees', type_='foreignkey')
    op.create_foreign_key(op.f('fk_profile_employees_user_id_auth_users'), 'profile_employees', 'auth_users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_profile_employees_email'), table_name='profile_employees')
    op.alter_column('profile_employees', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('profile_employees', 'phone')
    op.drop_column('profile_employees', 'email')
    op.drop_column('profile_employees', 'last_name')
    op.drop_column('profile_employees', 'first_name')
    op.drop_constraint(op.f('uq_intern_certificates_certificate_number'), 'intern_certificates', type_='unique')
    op.alter_column('intern_applications', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='PENDING, UNDER_REVIEW, ACCEPTED, REJECTED',
               existing_nullable=False)
    op.create_table_comment(
        'fin_payment_transactions',
        'Detailed log of payment gateway transactions',
        existing_comment='Detailed log of Razorpay payment records',
        schema=None
    )
    op.drop_index(op.f('ix_fin_payment_transactions_razorpay_payment_id'), table_name='fin_payment_transactions')
    op.drop_index(op.f('ix_fin_payment_transactions_razorpay_order_id'), table_name='fin_payment_transactions')
    op.drop_index(op.f('ix_fin_payment_transactions_order_id'), table_name='fin_payment_transactions')
    op.create_index(op.f('ix_fin_payment_transactions_order_id'), 'fin_payment_transactions', ['order_id'], unique=False)
    op.create_unique_constraint(op.f('uq_fin_payment_transactions_razorpay_payment_id'), 'fin_payment_transactions', ['razorpay_payment_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_fin_payment_transactions_razorpay_order_id'), 'fin_payment_transactions', ['razorpay_order_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_fin_payment_transactions_order_id'), 'fin_payment_transactions', ['order_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('fin_payment_transactions', 'gateway_response',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('fin_payment_transactions', 'status',
               existing_type=sa.VARCHAR(length=50),
               comment='SUCCESS, FAILED, PENDING',
               existing_comment='created, authorized, captured, failed, refunded',
               existing_nullable=False)
    op.alter_column('fin_payment_transactions', 'currency_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('comm_email_templates', 'status')
    op.drop_index(op.f('ix_alum_placement_opportunities_updated_by'), table_name='alum_placement_opportunities')
    op.drop_index(op.f('ix_alum_placement_opportunities_deleted_at'), table_name='alum_placement_opportunities')
    op.drop_index(op.f('ix_alum_placement_opportunities_created_by'), table_name='alum_placement_opportunities')
    op.drop_index(op.f('ix_alum_placement_opportunities_company_id'), table_name='alum_placement_opportunities')
    op.drop_table('alum_placement_opportunities')
    op.drop_index(op.f('ix_rbac_user_modules_user_id'), table_name='rbac_user_modules')
    op.drop_index(op.f('ix_rbac_user_modules_updated_by'), table_name='rbac_user_modules')
    op.drop_index(op.f('ix_rbac_user_modules_module_id'), table_name='rbac_user_modules')
    op.drop_index(op.f('ix_rbac_user_modules_deleted_at'), table_name='rbac_user_modules')
    op.drop_index(op.f('ix_rbac_user_modules_created_by'), table_name='rbac_user_modules')
    op.drop_table('rbac_user_modules')
    op.drop_index(op.f('ix_rbac_role_modules_updated_by'), table_name='rbac_role_modules')
    op.drop_index(op.f('ix_rbac_role_modules_role_id'), table_name='rbac_role_modules')
    op.drop_index(op.f('ix_rbac_role_modules_module_id'), table_name='rbac_role_modules')
    op.drop_index(op.f('ix_rbac_role_modules_deleted_at'), table_name='rbac_role_modules')
    op.drop_index(op.f('ix_rbac_role_modules_created_by'), table_name='rbac_role_modules')
    op.drop_table('rbac_role_modules')
    op.drop_index(op.f('ix_quiz_submissions_updated_by'), table_name='quiz_submissions')
    op.drop_index(op.f('ix_quiz_submissions_student_id'), table_name='quiz_submissions')
    op.drop_index(op.f('ix_quiz_submissions_deleted_at'), table_name='quiz_submissions')
    op.drop_index(op.f('ix_quiz_submissions_created_by'), table_name='quiz_submissions')
    op.drop_index(op.f('ix_quiz_submissions_assessment_id'), table_name='quiz_submissions')
    op.drop_table('quiz_submissions')
    op.drop_index(op.f('ix_prod_sticky_notes_user_id'), table_name='prod_sticky_notes')
    op.drop_index(op.f('ix_prod_sticky_notes_updated_by'), table_name='prod_sticky_notes')
    op.drop_index(op.f('ix_prod_sticky_notes_deleted_at'), table_name='prod_sticky_notes')
    op.drop_index(op.f('ix_prod_sticky_notes_created_by'), table_name='prod_sticky_notes')
    op.drop_table('prod_sticky_notes')
    op.drop_index(op.f('ix_prod_personal_tasks_user_id'), table_name='prod_personal_tasks')
    op.drop_index(op.f('ix_prod_personal_tasks_updated_by'), table_name='prod_personal_tasks')
    op.drop_index(op.f('ix_prod_personal_tasks_deleted_at'), table_name='prod_personal_tasks')
    op.drop_index(op.f('ix_prod_personal_tasks_created_by'), table_name='prod_personal_tasks')
    op.drop_table('prod_personal_tasks')
    op.drop_index(op.f('ix_prod_bookmarks_user_id'), table_name='prod_bookmarks')
    op.drop_index(op.f('ix_prod_bookmarks_updated_by'), table_name='prod_bookmarks')
    op.drop_index(op.f('ix_prod_bookmarks_deleted_at'), table_name='prod_bookmarks')
    op.drop_index(op.f('ix_prod_bookmarks_created_by'), table_name='prod_bookmarks')
    op.drop_table('prod_bookmarks')
    op.drop_index(op.f('ix_sys_reports_updated_by'), table_name='sys_reports')
    op.drop_index(op.f('ix_sys_reports_deleted_at'), table_name='sys_reports')
    op.drop_index(op.f('ix_sys_reports_created_by'), table_name='sys_reports')
    op.drop_table('sys_reports')
    op.drop_index(op.f('ix_quiz_assessments_updated_by'), table_name='quiz_assessments')
    op.drop_index(op.f('ix_quiz_assessments_frontend_id'), table_name='quiz_assessments')
    op.drop_index(op.f('ix_quiz_assessments_deleted_at'), table_name='quiz_assessments')
    op.drop_index(op.f('ix_quiz_assessments_created_by'), table_name='quiz_assessments')
    op.drop_table('quiz_assessments')
    op.drop_index(op.f('ix_comm_calendar_events_updated_by'), table_name='comm_calendar_events')
    op.drop_index(op.f('ix_comm_calendar_events_deleted_at'), table_name='comm_calendar_events')
    op.drop_index(op.f('ix_comm_calendar_events_created_by'), table_name='comm_calendar_events')
    op.drop_table('comm_calendar_events')
    op.drop_index(op.f('ix_cert_verification_requests_updated_by'), table_name='cert_verification_requests')
    op.drop_index(op.f('ix_cert_verification_requests_deleted_at'), table_name='cert_verification_requests')
    op.drop_index(op.f('ix_cert_verification_requests_created_by'), table_name='cert_verification_requests')
    op.drop_index(op.f('ix_cert_verification_requests_certificate_number'), table_name='cert_verification_requests')
    op.drop_table('cert_verification_requests')
    op.drop_index(op.f('ix_cert_certificates_updated_by'), table_name='cert_certificates')
    op.drop_index(op.f('ix_cert_certificates_deleted_at'), table_name='cert_certificates')
    op.drop_index(op.f('ix_cert_certificates_created_by'), table_name='cert_certificates')
    op.drop_index(op.f('ix_cert_certificates_certificate_number'), table_name='cert_certificates')
    op.drop_table('cert_certificates')
    op.drop_index(op.f('ix_analytics_kpis_updated_by'), table_name='analytics_kpis')
    op.drop_index(op.f('ix_analytics_kpis_deleted_at'), table_name='analytics_kpis')
    op.drop_index(op.f('ix_analytics_kpis_created_by'), table_name='analytics_kpis')
    op.drop_table('analytics_kpis')
    # ### end Alembic commands ###
