"""add route_path to modules

Revision ID: 73a08c5d1d64
Revises: d41c7d8e9a2b
Create Date: 2026-07-02 00:21:21.829293

NOTE: The original autogenerated migration contained ~7,800 lines of
COMMENT ON COLUMN DDL that consistently caused AWS RDS SSL connection
drops mid-transaction (the single transaction took 5+ minutes).
This file retains only the three real structural changes and strips the
cosmetic column-comment ALTER TABLE statements.  Column comments can be
re-applied later in a separate lightweight migration if desired.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '73a08c5d1d64'
down_revision: Union[str, None] = 'd41c7d8e9a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop the legacy rbac_user_modules table.
    # Uses IF EXISTS so re-runs are safe (table may have been dropped manually).
    op.execute(sa.text("DROP TABLE IF EXISTS rbac_user_modules CASCADE"))

    # Rename rbac_modules.path → route_path.
    # ADD COLUMN IF NOT EXISTS so re-runs are safe (column may already exist).
    op.execute(sa.text(
        "ALTER TABLE rbac_modules ADD COLUMN IF NOT EXISTS route_path VARCHAR(255)"
    ))
    # DROP COLUMN IF EXISTS so re-runs are safe.
    op.execute(sa.text(
        "ALTER TABLE rbac_modules DROP COLUMN IF EXISTS path"
    ))


def downgrade() -> None:
    # Reverse: restore path, drop route_path
    op.execute(sa.text(
        "ALTER TABLE rbac_modules ADD COLUMN IF NOT EXISTS path VARCHAR(255)"
    ))
    op.execute(sa.text(
        "ALTER TABLE rbac_modules DROP COLUMN IF EXISTS route_path"
    ))

    # Recreate rbac_user_modules
    op.create_table(
        'rbac_user_modules',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
        sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('module_id', sa.UUID(), autoincrement=False, nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
        sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
        sa.Column('updated_by', sa.UUID(), autoincrement=False, nullable=True),
        sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column('version_id', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(['module_id'], ['rbac_modules.id'], name=op.f('rbac_user_modules_module_id_fkey'), ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['auth_users.id'], name=op.f('rbac_user_modules_user_id_fkey'), ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name=op.f('rbac_user_modules_pkey')),
        sa.UniqueConstraint('user_id', 'module_id', name=op.f('uq_rbac_user_module'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    )
