"""add_blood_group_emergency_contact_to_profiles

Revision ID: ed23cf8348aa
Revises: 25aa00c1c5c9
Create Date: 2026-07-05 20:39:14.232174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ed23cf8348aa'
down_revision: Union[str, None] = '25aa00c1c5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile_employees', sa.Column('blood_group_id', sa.UUID(), nullable=True))
    op.add_column('profile_employees', sa.Column('emergency_contact', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_profile_employees_blood_group_id'), 'profile_employees', ['blood_group_id'], unique=False)
    op.create_foreign_key(op.f('fk_profile_employees_blood_group_id_ref_blood_groups'), 'profile_employees', 'ref_blood_groups', ['blood_group_id'], ['id'], ondelete='SET NULL')
    op.add_column('profile_students', sa.Column('blood_group_id', sa.UUID(), nullable=True))
    op.add_column('profile_students', sa.Column('emergency_contact', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_profile_students_blood_group_id'), 'profile_students', ['blood_group_id'], unique=False)
    op.create_foreign_key(op.f('fk_profile_students_blood_group_id_ref_blood_groups'), 'profile_students', 'ref_blood_groups', ['blood_group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_profile_students_blood_group_id_ref_blood_groups'), 'profile_students', type_='foreignkey')
    op.drop_index(op.f('ix_profile_students_blood_group_id'), table_name='profile_students')
    op.drop_column('profile_students', 'emergency_contact')
    op.drop_column('profile_students', 'blood_group_id')
    op.drop_constraint(op.f('fk_profile_employees_blood_group_id_ref_blood_groups'), 'profile_employees', type_='foreignkey')
    op.drop_index(op.f('ix_profile_employees_blood_group_id'), table_name='profile_employees')
    op.drop_column('profile_employees', 'emergency_contact')
    op.drop_column('profile_employees', 'blood_group_id')
    # ### end Alembic commands ###
