"""add internship_types

Revision ID: 7794293f740f
Revises: f8b649b35df9
Create Date: 2026-06-18 23:13:44.127956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7794293f740f'
down_revision: Union[str, Sequence[str], None] = 'f8b649b35df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internship_types',
    sa.Column('internship_type_id', sa.UUID(), nullable=False),
    sa.Column('type_code', sa.String(length=50), nullable=False),
    sa.Column('type_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('internship_type_id')
    )
    op.create_index(op.f('ix_internship_types_is_active'), 'internship_types', ['is_active'], unique=False)
    op.create_index(op.f('ix_internship_types_type_code'), 'internship_types', ['type_code'], unique=True)
    op.create_table('internship_openings',
    sa.Column('opening_id', sa.UUID(), nullable=False),
    sa.Column('internship_type_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.Column('role_description', sa.Text(), nullable=True),
    sa.Column('project_title', sa.String(length=255), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('stipend_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_openings', sa.Integer(), nullable=False),
    sa.Column('application_deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['internship_type_id'], ['internship_types.internship_type_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('opening_id')
    )
    op.create_index(op.f('ix_internship_openings_application_deadline'), 'internship_openings', ['application_deadline'], unique=False)
    op.create_index(op.f('ix_internship_openings_created_by'), 'internship_openings', ['created_by'], unique=False)
    op.create_index(op.f('ix_internship_openings_internship_type_id'), 'internship_openings', ['internship_type_id'], unique=False)
    op.create_index(op.f('ix_internship_openings_status'), 'internship_openings', ['status'], unique=False)
    op.create_table('applications',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('opening_id', sa.UUID(), nullable=False),
    sa.Column('applicant_user_id', sa.UUID(), nullable=False),
    sa.Column('application_status', sa.String(length=30), server_default='draft', nullable=False),
    sa.Column('applied_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['applicant_user_id'], ['users.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['opening_id'], ['internship_openings.opening_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('application_id'),
    sa.UniqueConstraint('opening_id', 'applicant_user_id', name='uq_application_unique')
    )
    op.create_index(op.f('ix_applications_applicant_user_id'), 'applications', ['applicant_user_id'], unique=False)
    op.create_index(op.f('ix_applications_application_status'), 'applications', ['application_status'], unique=False)
    op.create_index(op.f('ix_applications_applied_at'), 'applications', ['applied_at'], unique=False)
    op.create_index(op.f('ix_applications_opening_id'), 'applications', ['opening_id'], unique=False)
    op.create_index(op.f('ix_applications_reviewed_by'), 'applications', ['reviewed_by'], unique=False)
    op.create_table('application_documents',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_data', postgresql.BYTEA(), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_application_documents_application_id'), 'application_documents', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_documents_document_type'), 'application_documents', ['document_type'], unique=False)
    op.create_table('application_profiles',
    sa.Column('application_profile_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('college_name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('degree', sa.String(length=100), nullable=False),
    sa.Column('current_year', sa.SmallInteger(), nullable=False),
    sa.Column('cgpa_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('graduation_year', sa.SmallInteger(), nullable=False),
    sa.Column('skills', sa.Text(), nullable=False),
    sa.Column('github_url', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('portfolio_url', sa.Text(), nullable=True),
    sa.Column('project_experience', sa.Text(), nullable=True),
    sa.Column('motivation_statement', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('application_profile_id')
    )
    op.create_index(op.f('ix_application_profiles_application_id'), 'application_profiles', ['application_id'], unique=True)
    op.create_index(op.f('ix_application_profiles_college_name'), 'application_profiles', ['college_name'], unique=False)
    op.create_index(op.f('ix_application_profiles_email'), 'application_profiles', ['email'], unique=False)
    op.create_table('industrial_application_details',
    sa.Column('industrial_application_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('preferred_technology_stack', sa.Text(), nullable=False),
    sa.Column('relevant_technical_experience', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('industrial_application_id')
    )
    op.create_index(op.f('ix_industrial_application_details_application_id'), 'industrial_application_details', ['application_id'], unique=True)
    op.create_table('research_application_details',
    sa.Column('research_application_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('research_area_of_interest', sa.String(length=255), nullable=False),
    sa.Column('research_interest_statement', sa.Text(), nullable=False),
    sa.Column('publications_available', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('publication_links', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('research_application_id')
    )
    op.create_index(op.f('ix_research_application_details_application_id'), 'research_application_details', ['application_id'], unique=True)
    op.create_table('stipend_application_details',
    sa.Column('stipend_application_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('relevant_experience', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('stipend_application_id')
    )
    op.create_index(op.f('ix_stipend_application_details_application_id'), 'stipend_application_details', ['application_id'], unique=True)
    op.create_table('paid_application_details',
    sa.Column('paid_application_id', sa.UUID(), nullable=False),
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('fee_acceptance', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('payment_document_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['application_id'], ['applications.application_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_document_id'], ['application_documents.document_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('paid_application_id')
    )
    op.create_index(op.f('ix_paid_application_details_application_id'), 'paid_application_details', ['application_id'], unique=True)
    op.create_index(op.f('ix_paid_application_details_payment_status'), 'paid_application_details', ['payment_status'], unique=False)
    # op.create_unique_constraint('uq_user_single_role', 'user_roles', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_single_role', 'user_roles', type_='unique')
    op.drop_index(op.f('ix_paid_application_details_payment_status'), table_name='paid_application_details')
    op.drop_index(op.f('ix_paid_application_details_application_id'), table_name='paid_application_details')
    op.drop_table('paid_application_details')
    op.drop_index(op.f('ix_stipend_application_details_application_id'), table_name='stipend_application_details')
    op.drop_table('stipend_application_details')
    op.drop_index(op.f('ix_research_application_details_application_id'), table_name='research_application_details')
    op.drop_table('research_application_details')
    op.drop_index(op.f('ix_industrial_application_details_application_id'), table_name='industrial_application_details')
    op.drop_table('industrial_application_details')
    op.drop_index(op.f('ix_application_profiles_email'), table_name='application_profiles')
    op.drop_index(op.f('ix_application_profiles_college_name'), table_name='application_profiles')
    op.drop_index(op.f('ix_application_profiles_application_id'), table_name='application_profiles')
    op.drop_table('application_profiles')
    op.drop_index(op.f('ix_application_documents_document_type'), table_name='application_documents')
    op.drop_index(op.f('ix_application_documents_application_id'), table_name='application_documents')
    op.drop_table('application_documents')
    op.drop_index(op.f('ix_applications_reviewed_by'), table_name='applications')
    op.drop_index(op.f('ix_applications_opening_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_applied_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_application_status'), table_name='applications')
    op.drop_index(op.f('ix_applications_applicant_user_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_internship_openings_status'), table_name='internship_openings')
    op.drop_index(op.f('ix_internship_openings_internship_type_id'), table_name='internship_openings')
    op.drop_index(op.f('ix_internship_openings_created_by'), table_name='internship_openings')
    op.drop_index(op.f('ix_internship_openings_application_deadline'), table_name='internship_openings')
    op.drop_table('internship_openings')
    op.drop_index(op.f('ix_internship_types_type_code'), table_name='internship_types')
    op.drop_index(op.f('ix_internship_types_is_active'), table_name='internship_types')
    op.drop_table('internship_types')
    # ### end Alembic commands ###
