'use client';
import { useState } from 'react';
import { GeneratedDocument } from '@/src/types/document.types';
import { DocumentService } from '@/src/services/document.service';
import { FileText, Download, Eye, Send, Loader2, CheckCircle2 } from 'lucide-react';
import { Drawer } from '../ui/Drawer';

interface DocumentTableProps {
  documents: GeneratedDocument[];
  loading: boolean;
  onUpdate: () => void;
}

export default function DocumentTable({ documents, loading, onUpdate }: DocumentTableProps) {
  // Action state
  const [selectedDoc, setSelectedDoc] = useState<GeneratedDocument | null>(null);
  const [sendingId, setSendingId] = useState<string | null>(null);
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  const handleSendDocument = async (id: string) => {
    setSendingId(id);
    try {
      await DocumentService.updateDocumentStatus(id, 'Sent');
      onUpdate();
    } catch (e) {
      console.error(e);
    } finally {
      setSendingId(null);
    }
  };

  const handleDownload = (doc: GeneratedDocument) => {
    setDownloadingId(doc.id);
    setTimeout(() => {
      // Trigger a mock file download of a text/pdf layout
      const text = `%PDF-1.4\n% MOCK PDF representing Pinesphere document\n\nDocument ID: ${doc.id}\nDocument Type: ${doc.type}\nStudent: ${doc.studentName}\nProgram: ${doc.program}\nStipend: INR ${doc.metadata.stipend || '15000'}/month\nGenerated Date: ${new Date(doc.generatedDate).toLocaleString()}\nVersion: ${doc.version}\nStatus: ${doc.status}\n\nGenerated by Pinesphere SIMP system.`;
      
      const blob = new Blob([text], { type: 'application/pdf' });
      const url = window.URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${doc.type.replace(/\s+/g, '_')}_${doc.studentName.replace(/\s+/g, '_')}.pdf`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      setDownloadingId(null);
    }, 1200);
  };

  const getStatusBadge = (status: string) => {
    const map: Record<string, string> = {
      'Draft': 'bg-slate-100 text-slate-700 border-slate-200',
      'Generated': 'bg-blue-50 text-blue-700 border-blue-150',
      'Sent': 'bg-amber-50 text-amber-700 border-amber-150',
      'Signed': 'bg-emerald-50 text-emerald-700 border-emerald-150'
    };
    return (
      <span className={`px-2.5 py-0.5 rounded-full text-[10px] font-bold border uppercase tracking-wider ${map[status] || map.Draft}`}>
        {status}
      </span>
    );
  };

  return (
    <div className="bg-white border border-slate-100 rounded-2xl shadow-sm overflow-hidden mt-6 font-sans">
      <div className="p-4 border-b border-slate-100 flex justify-between items-center bg-slate-50/50">
        <h2 className="text-sm font-bold text-slate-800 tracking-tight flex items-center gap-2">
          <FileText className="h-5 w-5 text-indigo-650" /> Generated Documents Registry
        </h2>
      </div>
      
      <div className="overflow-x-auto">
        <table className="w-full text-xs text-slate-650 text-left">
          <thead className="bg-slate-50 text-[10px] uppercase font-bold tracking-wider text-slate-500 border-b border-slate-100">
            <tr>
              <th className="px-5 py-4 font-bold">Document Info</th>
              <th className="px-5 py-4 font-bold">Candidate / Subject</th>
              <th className="px-5 py-4 font-bold">Status</th>
              <th className="px-5 py-4 font-bold text-right">Actions</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {loading ? (
              <tr>
                <td colSpan={4} className="px-5 py-12 text-center text-slate-400 font-semibold">
                  <Loader2 className="w-6 h-6 animate-spin mx-auto mb-2" />
                  Loading generated documents...
                </td>
              </tr>
            ) : documents.map(doc => (
              <tr key={doc.id} className="hover:bg-slate-50/50 transition-colors">
                <td className="px-5 py-4">
                  <div className="flex flex-col">
                    <span className="font-bold text-slate-800 text-sm">{doc.type}</span>
                    <span className="text-[10px] text-slate-400 font-medium mt-0.5">Version: {doc.version}</span>
                    <span className="text-[9px] text-slate-400 font-mono mt-0.5">
                      {new Date(doc.generatedDate).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', hour: '2-digit', minute: '2-digit' })}
                    </span>
                  </div>
                </td>
                <td className="px-5 py-4">
                  <div className="flex flex-col">
                    <span className="font-bold text-slate-800">{doc.studentName}</span>
                    <span className="text-[10px] text-slate-500 font-medium">{doc.program}</span>
                  </div>
                </td>
                <td className="px-5 py-4">
                  {getStatusBadge(doc.status)}
                </td>
                <td className="px-5 py-4 text-right">
                  <div className="flex items-center justify-end gap-3 text-slate-400">
                    <button 
                      onClick={() => setSelectedDoc(doc)}
                      title="View Details"
                      className="p-1.5 hover:text-slate-900 bg-slate-50 rounded-lg hover:bg-slate-100 transition-colors cursor-pointer"
                    >
                      <Eye className="h-4 w-4" />
                    </button>
                    
                    <button 
                      onClick={() => handleDownload(doc)}
                      disabled={downloadingId === doc.id}
                      title="Download PDF"
                      className="p-1.5 hover:text-indigo-650 bg-slate-50 rounded-lg hover:bg-slate-100 transition-colors cursor-pointer disabled:opacity-50"
                    >
                      {downloadingId === doc.id ? (
                        <Loader2 className="h-4 w-4 animate-spin text-indigo-650" />
                      ) : (
                        <Download className="h-4 w-4" />
                      )}
                    </button>
                    
                    {doc.status !== 'Signed' && doc.status !== 'Sent' && (
                      <button 
                        onClick={() => handleSendDocument(doc.id)}
                        disabled={sendingId === doc.id}
                        title="Send via Email"
                        className="p-1.5 hover:text-emerald-600 bg-slate-50 rounded-lg hover:bg-slate-100 transition-colors cursor-pointer disabled:opacity-50"
                      >
                        {sendingId === doc.id ? (
                          <Loader2 className="h-4 w-4 animate-spin text-emerald-600" />
                        ) : (
                          <Send className="h-4 w-4" />
                        )}
                      </button>
                    )}
                  </div>
                </td>
              </tr>
            ))}
            {documents.length === 0 && !loading && (
              <tr>
                <td colSpan={4} className="px-5 py-8 text-center text-slate-400 font-medium">
                  No documents generated yet.
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>

      {/* --- DRAWERS --- */}

      {/* View Document Details Drawer */}
      <Drawer
        isOpen={selectedDoc !== null}
        onClose={() => setSelectedDoc(null)}
        title="Document Parameters & Details"
      >
        {selectedDoc && (
          <div className="p-6 space-y-6 overflow-y-auto font-sans">
            <div className="flex justify-between items-center bg-slate-50 border border-slate-150 p-4 rounded-2xl">
              <div>
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Document Registry ID</span>
                <h4 className="text-sm font-extrabold text-slate-800 font-mono mt-0.5">{selectedDoc.id}</h4>
              </div>
              <div>{getStatusBadge(selectedDoc.status)}</div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Document Type</span>
                <p className="text-xs font-bold text-slate-700">{selectedDoc.type}</p>
              </div>
              <div className="space-y-1">
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">File Format</span>
                <p className="text-xs font-bold text-slate-700">Adobe PDF (.pdf)</p>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-1">
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Candidate Name</span>
                <p className="text-xs font-bold text-slate-700">{selectedDoc.studentName}</p>
              </div>
              <div className="space-y-1">
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider">Training Program</span>
                <p className="text-xs font-bold text-slate-700">{selectedDoc.program}</p>
              </div>
            </div>

            <div className="pt-3.5 border-t border-slate-100 space-y-3">
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">Document Attributes (Metadata)</span>
              
              <div className="bg-slate-50 rounded-xl p-3.5 space-y-2 border border-slate-150">
                {Object.entries(selectedDoc.metadata).map(([key, value]) => (
                  <div key={key} className="flex justify-between text-xs">
                    <span className="text-slate-400 font-bold uppercase tracking-wider text-[9px]">{key}:</span>
                    <span className="text-slate-700 font-bold">{value}</span>
                  </div>
                ))}
                <div className="flex justify-between text-xs pt-1 border-t border-slate-150">
                  <span className="text-slate-400 font-bold uppercase tracking-wider text-[9px]">version:</span>
                  <span className="text-slate-700 font-bold">{selectedDoc.version}</span>
                </div>
                <div className="flex justify-between text-xs">
                  <span className="text-slate-400 font-bold uppercase tracking-wider text-[9px]">generated date:</span>
                  <span className="text-slate-750 font-mono text-[10px]">{new Date(selectedDoc.generatedDate).toLocaleString()}</span>
                </div>
              </div>
            </div>

            <div className="flex gap-3 pt-4 border-t border-slate-100 mt-auto">
              <button
                type="button"
                onClick={() => setSelectedDoc(null)}
                className="flex-1 py-3 border border-slate-200 text-slate-700 font-bold text-xs rounded-xl hover:bg-slate-50 transition-colors cursor-pointer"
              >
                Close Details
              </button>
              <button
                type="button"
                onClick={() => {
                  handleDownload(selectedDoc);
                  setSelectedDoc(null);
                }}
                className="flex-1 py-3 bg-slate-900 hover:bg-black text-white font-bold text-xs rounded-xl transition-all flex items-center justify-center gap-1.5 cursor-pointer shadow-lg shadow-slate-900/10"
              >
                <Download className="w-3.5 h-3.5" />
                Download PDF
              </button>
            </div>
          </div>
        )}
      </Drawer>

    </div>
  );
}
