"""
PDF Generator Utility for Pinesphere SIMP ERP
Generates professional, branded PDF documents and reports using reportlab.
"""
import io
import random
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import inch, mm
from reportlab.lib.colors import HexColor, black, white
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, Frame, PageTemplate, BaseDocTemplate
)
from reportlab.pdfgen import canvas


# ──────────────────────────────────────────────
# Brand constants
# ──────────────────────────────────────────────
BRAND_NAME = "Pinesphere"
BRAND_TAGLINE = "Enterprise Learning & Workforce Management"
BRAND_ADDRESS = "Tower-B, 14th Floor, Cyber Gateway, HITEC City, Hyderabad — 500081, India"
BRAND_WEBSITE = "www.pinesphere.io"
BRAND_EMAIL = "admin@pinesphere.io"
BRAND_PHONE = "+91-40-6789-0123"

PRIMARY_COLOR = HexColor("#1e293b")     # Slate-800
ACCENT_COLOR = HexColor("#4f46e5")      # Indigo-600
LIGHT_BG = HexColor("#f8fafc")          # Slate-50
BORDER_COLOR = HexColor("#e2e8f0")      # Slate-200
TEXT_SECONDARY = HexColor("#64748b")     # Slate-500


# ──────────────────────────────────────────────
# Shared header/footer drawing
# ──────────────────────────────────────────────
def _draw_header(c: canvas.Canvas, width, height):
    """Draw branded header on every page."""
    c.saveState()
    # Header bar background
    c.setFillColor(PRIMARY_COLOR)
    c.rect(0, height - 72, width, 72, fill=1, stroke=0)

    # Brand name
    c.setFillColor(white)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(40, height - 35, BRAND_NAME.upper())

    # Tagline
    c.setFont("Helvetica", 8)
    c.setFillColor(HexColor("#94a3b8"))
    c.drawString(40, height - 50, BRAND_TAGLINE)

    # Right side: date
    c.setFillColor(HexColor("#cbd5e1"))
    c.setFont("Helvetica", 8)
    c.drawRightString(width - 40, height - 35, datetime.now().strftime("%B %d, %Y"))
    c.drawRightString(width - 40, height - 50, f"Ref: PS/{datetime.now().strftime('%Y%m%d')}/{random.randint(1000, 9999)}")

    # Thin accent line under header
    c.setStrokeColor(ACCENT_COLOR)
    c.setLineWidth(2)
    c.line(0, height - 72, width, height - 72)

    c.restoreState()


def _draw_footer(c: canvas.Canvas, width, height):
    """Draw branded footer on every page."""
    c.saveState()

    # Footer line
    c.setStrokeColor(BORDER_COLOR)
    c.setLineWidth(0.5)
    c.line(40, 55, width - 40, 55)

    # Footer text
    c.setFont("Helvetica", 7)
    c.setFillColor(TEXT_SECONDARY)
    c.drawString(40, 42, f"{BRAND_NAME} • {BRAND_ADDRESS}")
    c.drawString(40, 32, f"Email: {BRAND_EMAIL}  |  Phone: {BRAND_PHONE}  |  Web: {BRAND_WEBSITE}")

    # Page number
    c.setFont("Helvetica-Bold", 7)
    c.setFillColor(ACCENT_COLOR)
    c.drawRightString(width - 40, 42, f"Page {c.getPageNumber()}")

    # Confidentiality notice
    c.setFont("Helvetica-Oblique", 6)
    c.setFillColor(TEXT_SECONDARY)
    c.drawCentredString(width / 2, 20, "This document is auto-generated by Pinesphere SIMP and is confidential. Unauthorized distribution is prohibited.")

    c.restoreState()


def _build_pdf(draw_content_fn, title: str = "Document") -> bytes:
    """Scaffold a PDF with header/footer, call draw_content_fn for body."""
    buf = io.BytesIO()
    width, height = A4

    c = canvas.Canvas(buf, pagesize=A4)
    c.setTitle(title)
    c.setAuthor(BRAND_NAME)

    _draw_header(c, width, height)
    _draw_footer(c, width, height)
    draw_content_fn(c, width, height)
    c.save()

    buf.seek(0)
    return buf.read()


# ──────────────────────────────────────────────
# Document Templates
# ──────────────────────────────────────────────

def generate_offer_letter(student_name: str, program: str, stipend: str = "15000", date: str = None) -> bytes:
    """Generate a professional Offer Letter PDF."""
    gen_date = date or datetime.now().strftime("%B %d, %Y")

    def draw(c: canvas.Canvas, w, h):
        y = h - 110

        # Title
        c.setFont("Helvetica-Bold", 16)
        c.setFillColor(PRIMARY_COLOR)
        c.drawString(40, y, "OFFER LETTER")
        y -= 8
        c.setStrokeColor(ACCENT_COLOR)
        c.setLineWidth(2)
        c.line(40, y, 200, y)
        y -= 30

        # Date & recipient
        c.setFont("Helvetica", 10)
        c.setFillColor(TEXT_SECONDARY)
        c.drawString(40, y, f"Date: {gen_date}")
        y -= 25

        c.setFont("Helvetica-Bold", 11)
        c.setFillColor(PRIMARY_COLOR)
        c.drawString(40, y, f"To: {student_name}")
        y -= 18
        c.setFont("Helvetica", 10)
        c.setFillColor(TEXT_SECONDARY)
        c.drawString(40, y, f"Program: {program}")
        y -= 35

        # Subject line
        c.setFont("Helvetica-Bold", 11)
        c.setFillColor(PRIMARY_COLOR)
        c.drawString(40, y, f"Subject: Offer of Training — {program}")
        y -= 30

        # Body
        c.setFont("Helvetica", 10)
        c.setFillColor(black)
        body_lines = [
            f"Dear {student_name},",
            "",
            f"We are pleased to extend this offer of enrollment in the {program} training program",
            f"at {BRAND_NAME}. After careful review of your application and assessment results, we are",
            "confident that you will be an excellent addition to our learning cohort.",
            "",
            "The details of this offer are as follows:",
        ]
        for line in body_lines:
            c.drawString(40, y, line)
            y -= 16

        y -= 10

        # Details table
        details = [
            ["Program", program],
            ["Monthly Stipend", f"INR {stipend}/-"],
            ["Duration", "6 Months"],
            ["Start Date", "Upon acceptance of this offer"],
            ["Location", "HITEC City Campus, Hyderabad"],
            ["Reporting To", "Program Coordinator"],
        ]

        t = Table(details, colWidths=[160, 300])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), LIGHT_BG),
            ('TEXTCOLOR', (0, 0), (0, -1), PRIMARY_COLOR),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        tw, th = t.wrap(0, 0)
        t.drawOn(c, 40, y - th)
        y = y - th - 25

        # Terms
        terms_lines = [
            "Terms & Conditions:",
            "1. This offer is contingent upon successful identity verification and document submission.",
            "2. The stipend is subject to applicable tax deductions as per Indian tax law.",
            "3. You are expected to maintain a minimum attendance of 85% throughout the program.",
            "4. Any violation of the code of conduct may result in immediate termination.",
            "",
            "Please confirm your acceptance by signing and returning this letter within 7 business days.",
            "",
            "",
            "Warm Regards,",
        ]
        c.setFont("Helvetica", 9)
        c.setFillColor(PRIMARY_COLOR)
        for line in terms_lines:
            c.drawString(40, y, line)
            y -= 14

        # Signature area
        y -= 10
        c.setFont("Helvetica-Bold", 11)
        c.setFillColor(ACCENT_COLOR)
        c.drawString(40, y, "Program Director")
        y -= 14
        c.setFont("Helvetica", 9)
        c.setFillColor(TEXT_SECONDARY)
        c.drawString(40, y, BRAND_NAME)

    return _build_pdf(draw, f"Offer Letter — {student_name}")


def generate_joining_letter(student_name: str, program: str, date: str = None) -> bytes:
    """Generate a professional Joining Letter PDF."""
    gen_date = date or datetime.now().strftime("%B %d, %Y")

    def draw(c: canvas.Canvas, w, h):
        y = h - 110

        c.setFont("Helvetica-Bold", 16)
        c.setFillColor(PRIMARY_COLOR)
        c.drawString(40, y, "JOINING LETTER")
        y -= 8
        c.setStrokeColor(ACCENT_COLOR)
        c.setLineWidth(2)
        c.line(40, y, 220, y)
        y -= 30

        c.setFont("Helvetica", 10)
        c.setFillColor(TEXT_SECONDARY)
        c.drawString(40, y, f"Date: {gen_date}")
        y -= 25

        c.setFont("Helvetica-Bold", 11)
        c.setFillColor(PRIMARY_COLOR)
        c.drawString(40, y, f"To: {student_name}")
        y -= 18
        c.setFont("Helvetica", 10)
        c.setFillColor(TEXT_SECONDARY)
        c.drawString(40, y, f"Program: {program}")
        y -= 35

        c.setFont("Helvetica-Bold", 11)
        c.setFillColor(PRIMARY_COLOR)
        c.drawString(40, y, f"Subject: Confirmation of Joining — {program}")
        y -= 30

        c.setFont("Helvetica", 10)
        c.setFillColor(black)
        body = [
            f"Dear {student_name},",
            "",
            f"This letter confirms that you have officially joined the {program} training program",
            f"at {BRAND_NAME}, effective from {gen_date}.",
            "",
            "We are delighted to welcome you to our learning community. During the course of your",
            "engagement, you will be guided by experienced mentors and industry professionals who",
            "will help you build the skills necessary for a successful career.",
            "",
            "Please report to the designated campus location as communicated to you. Ensure you carry",
            "all required identification documents and the signed copy of your offer letter.",
            "",
            "Key information for your first day:",
        ]
        for line in body:
            c.drawString(40, y, line)
            y -= 16

        y -= 10
        info = [
            ["Reporting Time", "09:30 AM IST"],
            ["Location", "HITEC City Campus, Tower-B, 14th Floor"],
            ["Contact Person", "Ms. Priya Sharma, Program Coordinator"],
            ["Required Documents", "Aadhar Card, PAN Card, Passport-size Photo"],
            ["Dress Code", "Business Casual / Smart Casuals"],
        ]
        t = Table(info, colWidths=[160, 300])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), LIGHT_BG),
            ('TEXTCOLOR', (0, 0), (0, -1), PRIMARY_COLOR),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('GRID', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('LEFTPADDING', (0, 0), (-1, -1), 10),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ]))
        tw, th = t.wrap(0, 0)
        t.drawOn(c, 40, y - th)
        y = y - th - 30

        c.setFont("Helvetica", 9)
        c.setFillColor(PRIMARY_COLOR)
        closing = [
            "We wish you the very best in your learning journey.",
            "",
            "",
            "Warm Regards,",
        ]
        for line in closing:
            c.drawString(40, y, line)
            y -= 14

        y -= 10
        c.setFont("Helvetica-Bold", 11)
        c.setFillColor(ACCENT_COLOR)
        c.drawString(40, y, "HR & Administration Department")
        y -= 14
        c.setFont("Helvetica", 9)
        c.setFillColor(TEXT_SECONDARY)
        c.drawString(40, y, BRAND_NAME)

    return _build_pdf(draw, f"Joining Letter — {student_name}")


def generate_completion_certificate(student_name: str, program: str, duration: str = "6 Months", date: str = None) -> bytes:
    """Generate a professional Completion Certificate PDF."""
    gen_date = date or datetime.now().strftime("%B %d, %Y")

    def draw(c: canvas.Canvas, w, h):
        # Decorative border
        c.setStrokeColor(ACCENT_COLOR)
        c.setLineWidth(3)
        c.rect(25, 80, w - 50, h - 155, fill=0, stroke=1)
        c.setStrokeColor(BORDER_COLOR)
        c.setLineWidth(1)
        c.rect(30, 85, w - 60, h - 165, fill=0, stroke=1)

        y = h - 140

        # Certificate title
        c.setFont("Helvetica-Bold", 24)
        c.setFillColor(PRIMARY_COLOR)
        c.drawCentredString(w / 2, y, "CERTIFICATE OF COMPLETION")
        y -= 12
        c.setStrokeColor(ACCENT_COLOR)
        c.setLineWidth(2)
        c.line(w / 2 - 120, y, w / 2 + 120, y)
        y -= 40

        # Body
        c.setFont("Helvetica", 11)
        c.setFillColor(TEXT_SECONDARY)
        c.drawCentredString(w / 2, y, "This is to certify that")
        y -= 35

        c.setFont("Helvetica-Bold", 20)
        c.setFillColor(ACCENT_COLOR)
        c.drawCentredString(w / 2, y, student_name.upper())
        y -= 12
        c.setStrokeColor(PRIMARY_COLOR)
        c.setLineWidth(0.5)
        c.line(w / 2 - 100, y, w / 2 + 100, y)
        y -= 35

        c.setFont("Helvetica", 11)
        c.setFillColor(black)
        c.drawCentredString(w / 2, y, "has successfully completed the training program in")
        y -= 30

        c.setFont("Helvetica-Bold", 14)
        c.setFillColor(PRIMARY_COLOR)
        c.drawCentredString(w / 2, y, f'"{program}"')
        y -= 30

        c.setFont("Helvetica", 11)
        c.setFillColor(black)
        c.drawCentredString(w / 2, y, f"with a duration of {duration}, conducted by {BRAND_NAME}.")
        y -= 20
        c.drawCentredString(w / 2, y, f"Date of completion: {gen_date}")
        y -= 50

        # Performance summary
        c.setFont("Helvetica", 10)
        c.setFillColor(TEXT_SECONDARY)
        c.drawCentredString(w / 2, y, "The candidate demonstrated consistent dedication, strong technical aptitude,")
        y -= 16
        c.drawCentredString(w / 2, y, "and professional conduct throughout the duration of the program.")
        y -= 50

        # Signature blocks
        c.setFont("Helvetica", 8)
        c.setFillColor(TEXT_SECONDARY)
        c.setStrokeColor(PRIMARY_COLOR)
        c.setLineWidth(0.5)

        # Left signature
        c.line(80, y + 10, 220, y + 10)
        c.drawCentredString(150, y - 5, "Program Director")
        c.setFont("Helvetica-Bold", 8)
        c.drawCentredString(150, y - 18, BRAND_NAME)

        # Right signature
        c.setFont("Helvetica", 8)
        c.line(w - 220, y + 10, w - 80, y + 10)
        c.drawCentredString(w - 150, y - 5, "Academic Head")
        c.setFont("Helvetica-Bold", 8)
        c.drawCentredString(w - 150, y - 18, BRAND_NAME)

    return _build_pdf(draw, f"Completion Certificate — {student_name}")


def generate_recommendation_letter(student_name: str, program: str, date: str = None) -> bytes:
    """Generate a professional Recommendation Letter PDF."""
    gen_date = date or datetime.now().strftime("%B %d, %Y")

    def draw(c: canvas.Canvas, w, h):
        y = h - 110

        c.setFont("Helvetica-Bold", 16)
        c.setFillColor(PRIMARY_COLOR)
        c.drawString(40, y, "LETTER OF RECOMMENDATION")
        y -= 8
        c.setStrokeColor(ACCENT_COLOR)
        c.setLineWidth(2)
        c.line(40, y, 300, y)
        y -= 30

        c.setFont("Helvetica", 10)
        c.setFillColor(TEXT_SECONDARY)
        c.drawString(40, y, f"Date: {gen_date}")
        y -= 25

        c.setFont("Helvetica-Bold", 11)
        c.setFillColor(PRIMARY_COLOR)
        c.drawString(40, y, "To Whom It May Concern,")
        y -= 35

        c.setFont("Helvetica", 10)
        c.setFillColor(black)
        body = [
            f"I am writing to recommend {student_name}, who has recently completed the",
            f"{program} training program at {BRAND_NAME}.",
            "",
            f"During their tenure, {student_name} demonstrated exceptional aptitude, dedication,",
            "and a genuine passion for learning. They consistently exceeded expectations in both",
            "individual assignments and collaborative team projects.",
            "",
            "Key strengths observed during the training program include:",
        ]
        for line in body:
            c.drawString(40, y, line)
            y -= 16

        y -= 8
        strengths = [
            "•  Strong analytical and problem-solving capabilities",
            "•  Excellent communication and interpersonal skills",
            "•  Consistent punctuality and attendance record above 95%",
            "•  Proactive participation in workshops, hackathons, and peer mentoring",
            "•  Ability to adapt quickly to new technologies and frameworks",
        ]
        c.setFont("Helvetica", 10)
        for s in strengths:
            c.drawString(60, y, s)
            y -= 16

        y -= 10
        c.setFont("Helvetica", 10)
        closing = [
            f"Based on their performance, I am confident that {student_name} will be a valuable",
            "asset to any organization. I wholeheartedly recommend them for any professional role",
            "that aligns with their skillset and career aspirations.",
            "",
            "Please do not hesitate to contact me should you require any additional information.",
            "",
            "",
            "Sincerely,",
        ]
        for line in closing:
            c.drawString(40, y, line)
            y -= 14

        y -= 12
        c.setFont("Helvetica-Bold", 11)
        c.setFillColor(ACCENT_COLOR)
        c.drawString(40, y, "Program Director")
        y -= 14
        c.setFont("Helvetica", 9)
        c.setFillColor(TEXT_SECONDARY)
        c.drawString(40, y, BRAND_NAME)
        y -= 12
        c.drawString(40, y, BRAND_EMAIL)

    return _build_pdf(draw, f"Recommendation Letter — {student_name}")


# ──────────────────────────────────────────────
# Report Templates
# ──────────────────────────────────────────────

def _draw_report_body(c: canvas.Canvas, w, h, title: str, category: str, rows: list[list[str]], summary_lines: list[str]):
    """Shared helper for all report PDFs."""
    y = h - 110

    # Report title
    c.setFont("Helvetica-Bold", 16)
    c.setFillColor(PRIMARY_COLOR)
    c.drawString(40, y, title.upper())
    y -= 8
    c.setStrokeColor(ACCENT_COLOR)
    c.setLineWidth(2)
    c.line(40, y, 40 + len(title) * 9, y)
    y -= 25

    # Category & date
    c.setFont("Helvetica", 10)
    c.setFillColor(TEXT_SECONDARY)
    c.drawString(40, y, f"Category: {category}  |  Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}")
    y -= 15
    c.drawString(40, y, f"Generated By: Administrator Console  |  Format: PDF")
    y -= 30

    # Executive summary
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(PRIMARY_COLOR)
    c.drawString(40, y, "EXECUTIVE SUMMARY")
    y -= 18

    c.setFont("Helvetica", 9)
    c.setFillColor(black)
    for line in summary_lines:
        c.drawString(40, y, line)
        y -= 14
    y -= 15

    # Data table
    c.setFont("Helvetica-Bold", 11)
    c.setFillColor(PRIMARY_COLOR)
    c.drawString(40, y, "DETAILED BREAKDOWN")
    y -= 20

    col_count = len(rows[0]) if rows else 3
    col_width = (w - 80) / col_count
    t = Table(rows, colWidths=[col_width] * col_count)
    t.setStyle(TableStyle([
        # Header row
        ('BACKGROUND', (0, 0), (-1, 0), PRIMARY_COLOR),
        ('TEXTCOLOR', (0, 0), (-1, 0), white),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 9),
        # Body rows
        ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 1), (-1, -1), 9),
        ('TEXTCOLOR', (0, 1), (-1, -1), black),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [white, LIGHT_BG]),
        # Grid
        ('GRID', (0, 0), (-1, -1), 0.5, BORDER_COLOR),
        ('TOPPADDING', (0, 0), (-1, -1), 7),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 7),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
    ]))

    tw, th = t.wrap(0, 0)
    if y - th < 80:
        # If table is too tall, just draw what fits
        t.drawOn(c, 40, max(80, y - th))
    else:
        t.drawOn(c, 40, y - th)
    y = y - th - 30

    # Notes
    if y > 120:
        c.setFont("Helvetica-Bold", 9)
        c.setFillColor(PRIMARY_COLOR)
        c.drawString(40, y, "NOTES & DISCLAIMERS")
        y -= 16
        c.setFont("Helvetica-Oblique", 8)
        c.setFillColor(TEXT_SECONDARY)
        c.drawString(40, y, "• Data is compiled from the Pinesphere SIMP enterprise database and may be subject to real-time variance.")
        y -= 12
        c.drawString(40, y, "• All financial figures are in INR and exclude applicable taxes unless stated otherwise.")
        y -= 12
        c.drawString(40, y, "• This report is auto-generated and does not constitute audited financial advice.")


def generate_finance_report(report_name: str, date: str = None) -> bytes:
    """Generate Quarterly Finance Audit Report PDF."""
    rows = [
        ["Category", "Q1 Amount (INR)", "Q2 Amount (INR)", "Variance"],
        ["Tuition Fees Collected", "42,50,000", "45,75,000", "+7.6%"],
        ["Stipend Disbursements", "12,30,000", "13,50,000", "+9.8%"],
        ["Infrastructure Costs", "8,45,000", "8,20,000", "-3.0%"],
        ["Learning Materials", "3,20,000", "3,55,000", "+10.9%"],
        ["Administrative Overhead", "5,60,000", "5,85,000", "+4.5%"],
        ["Net Revenue", "12,95,000", "14,65,000", "+13.1%"],
        ["Outstanding Receivables", "4,10,000", "3,25,000", "-20.7%"],
    ]
    summary = [
        f"This report provides a comprehensive financial overview for {BRAND_NAME} operations.",
        "Overall revenue shows a positive upward trend of 13.1% compared to the previous quarter.",
        "Stipend disbursements increased proportionally with the growing cohort size.",
        "Outstanding receivables decreased by 20.7%, indicating improved collection efficiency.",
    ]
    def draw(c, w, h):
        _draw_report_body(c, w, h, report_name, "Financial", rows, summary)
    return _build_pdf(draw, report_name)


def generate_performance_report(report_name: str, date: str = None) -> bytes:
    """Generate Student Performance Report PDF."""
    rows = [
        ["Student / Cohort", "Module", "Avg Score", "Quiz Attempts", "Grade"],
        ["Cohort A (Web Dev)", "HTML & CSS Fundamentals", "87.3", "156", "A"],
        ["Cohort A (Web Dev)", "JavaScript Advanced", "78.9", "142", "B+"],
        ["Cohort A (Web Dev)", "React & Next.js", "82.1", "138", "A-"],
        ["Cohort B (Data Sci)", "Python for Data Science", "91.2", "120", "A+"],
        ["Cohort B (Data Sci)", "Machine Learning Basics", "76.4", "115", "B"],
        ["Cohort B (Data Sci)", "Deep Learning & Neural Networks", "73.8", "98", "B"],
        ["Cohort C (DevOps)", "Linux & Shell Scripting", "88.5", "80", "A"],
        ["Cohort C (DevOps)", "CI/CD Pipelines", "84.2", "75", "A-"],
    ]
    summary = [
        "This report consolidates student performance data across all active training cohorts.",
        "Cohort B (Data Science) leads in average scores with Python fundamentals at 91.2%.",
        "Quiz completion rates remain above 85% across all modules.",
        "Attention needed: Deep Learning module shows lower engagement — recommend additional workshops.",
    ]
    def draw(c, w, h):
        _draw_report_body(c, w, h, report_name, "Academic", rows, summary)
    return _build_pdf(draw, report_name)


def generate_attendance_report(report_name: str, date: str = None) -> bytes:
    """Generate Batch Attendance Ledger Report PDF."""
    rows = [
        ["Batch / Cohort", "Total Students", "Avg Attendance %", "Below 85%", "Status"],
        ["Web Dev — Cohort A", "45", "91.3%", "4", "Healthy"],
        ["Web Dev — Cohort B", "38", "87.8%", "6", "Moderate"],
        ["Data Science — Cohort A", "42", "93.5%", "2", "Healthy"],
        ["DevOps — Cohort A", "30", "89.1%", "3", "Healthy"],
        ["Product Design — Cohort A", "25", "84.2%", "8", "At Risk"],
        ["Cloud Engineering — Cohort A", "35", "90.7%", "3", "Healthy"],
    ]
    summary = [
        "This report summarizes attendance metrics across all active batches and cohorts.",
        "Overall average attendance stands at 89.4%, exceeding the minimum threshold of 85%.",
        "Product Design Cohort A shows concerning patterns with 32% of students below the threshold.",
        "Automated alerts have been triggered for students with attendance below 80%.",
    ]
    def draw(c, w, h):
        _draw_report_body(c, w, h, report_name, "Attendance", rows, summary)
    return _build_pdf(draw, report_name)


def generate_placement_report(report_name: str, date: str = None) -> bytes:
    """Generate Placement Velocity Summary Report PDF."""
    rows = [
        ["Company Partner", "Tier", "Openings", "Applications", "Selected", "Avg CTC (LPA)"],
        ["TCS Digital", "Tier-1", "15", "89", "12", "7.5"],
        ["Infosys Springboard", "Tier-1", "20", "125", "18", "6.8"],
        ["Wipro Elite", "Tier-1", "10", "67", "8", "6.2"],
        ["Zoho Corporation", "Tier-1", "8", "56", "6", "8.5"],
        ["Accenture Advanced", "Tier-2", "25", "142", "22", "5.5"],
        ["Cognizant GenC", "Tier-2", "30", "168", "26", "4.8"],
        ["Startups (Misc.)", "Tier-3", "40", "95", "35", "4.2"],
    ]
    summary = [
        "This report tracks hiring velocities, partner engagement, and CTC metrics for the current cycle.",
        "Total placements achieved: 127 out of 148 openings (85.8% fill rate).",
        "Tier-1 companies account for 34.6% of all selections with significantly higher CTC averages.",
        "Average CTC across all tiers stands at INR 6.21 LPA — a 12% increase over the previous cycle.",
    ]
    def draw(c, w, h):
        _draw_report_body(c, w, h, report_name, "Placement", rows, summary)
    return _build_pdf(draw, report_name)


# ──────────────────────────────────────────────
# Dispatcher maps
# ──────────────────────────────────────────────

DOCUMENT_GENERATORS = {
    "Offer Letter": generate_offer_letter,
    "Joining Letter": generate_joining_letter,
    "Completion Certificate": generate_completion_certificate,
    "Recommendation Letter": generate_recommendation_letter,
    "Internship Letter": generate_offer_letter,  # Reuse offer letter layout for internships
}

REPORT_GENERATORS = {
    "Financial": generate_finance_report,
    "Academic": generate_performance_report,
    "Attendance": generate_attendance_report,
    "Placement": generate_placement_report,
}
